services:
  - type: web
    name: job-scraper
    env: python
    plan: free
    buildCommand: |
      ./build.sh
      pip install -r requirements.txt
      playwright install
    startCommand: "python app.py"